language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      before_install:
        # - brew update
        # - brew tap caskroom/cask
        - brew cask install powershell
    - os: linux
      dist: trusty
      # VM-based builds turned out to be faster
      sudo: required
      addons:
        apt:
          sources:
            - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main
              key_url: https://packages.microsoft.com/keys/microsoft.asc
          packages:
            - powershell

script:
  - sudo pwsh -C 'Install-Module Pester -Force'
  # updated help is needed for tests, run as a Job to avoid Write-Progress output
  - sudo pwsh -C '(update-help &) | Wait-Job'
  - pwsh -C 'Import-Module Pester;cd .\Bookmarks\; Invoke-Pester -EnableExit;'