trigger:
  - master
pr:
  - master

resources:
  - repo: self
    clean: true
    fetchDepth: 1

jobs:
  - job: PowerShell2
    pool:
      vmImage: 'vs2015-win2012r2'
    displayName: PowerShell 2
    continueOnError: false
    workspace:
      clean: all
    timeoutInMinutes: 3
    steps:
      - script: |
          rem build in 32-bit version of PowerShell 2 because the 64-bit version
          rem was butchered and replaced with PowerShell 6 to be able to run the
          rem Azure Pipelines agent on Server 2008 R2 with only PowerShell 2
          C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe -c "$errorActionPreference = 'stop'; $global:PesterDebugPreference_ShowFullErrors = $true ; try {$PSVersionTable; Set-StrictMode -Version Latest; Install-Module -Name Pester -Force;Import-Module Pester;. .\Bookmarks\Bookmarks.Tests.ps1} catch { Write-Error $_; exit 9999 }"
          exit %errorlevel%
  - job: PowerShell3
    displayName: PowerShell 3
    continueOnError: false
    pool:
      vmImage: 'windows-2019'
    workspace:
      clean: all
    timeoutInMinutes: 3
    steps:
      - powershell: |
          $global:PesterDebugPreference_ShowFullErrors = $true
          $errorActionPreference = 'stop'
          Set-StrictMode -Version Latest
          Install-Module -Name Pester -Force
          Import-Module Pester
          . .\Bookmarks\Bookmarks.Tests.ps1